spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:~/data/invoice
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2